# Generated by Django 5.1.1 on 2024-11-22 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="LLMModel",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "version_name",
                    models.CharField(
                        help_text="The version name of the model", max_length=100
                    ),
                ),
                (
                    "display_name",
                    models.CharField(
                        help_text="The display name of the model", max_length=100
                    ),
                ),
                (
                    "provider",
                    models.CharField(
                        choices=[("openai", "OpenAI"), ("bedrock", "AWS Bedrock")],
                        help_text="The provider of the model",
                        max_length=20,
                    ),
                ),
                (
                    "is_enabled",
                    models.BooleanField(
                        default=True, help_text="Whether the model is enabled"
                    ),
                ),
                (
                    "is_multimodal",
                    models.BooleanField(
                        default=False, help_text="Whether the model supports images"
                    ),
                ),
                (
                    "is_function_calling_supported",
                    models.BooleanField(
                        default=False,
                        help_text="Whether the model supports function calling",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="The description of the model"
                    ),
                ),
                (
                    "settings",
                    models.JSONField(
                        blank=True,
                        default=dict,
                        help_text="The settings of the model",
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "LLM Model",
                "verbose_name_plural": "LLM Models",
                "ordering": ["provider", "display_name", "version_name"],
                "unique_together": {("provider", "version_name")},
            },
        ),
    ]
